### ISSUE TITLE
Deadlock when posting events synchronized in background

### ISSUE THREAD

**Issue by chomps1** [spinettaro/delphi-event-bus#25]
Dear Danielle.
I try to process as much as possible in background. The event bus is perfect for simplifying my code. I'm using some additional libraries for some reason, and I get synchronized (Delphi-) events from those libraries. I would like to post some of the processing into background, but unfortunately the eventbus post gets into deadlock. I prepared a simplified test for reproduction. As a workaround I removed the critical section from your code in post routine, because I can't see any disadvantage. But maybe you can explain, what you wanted to avoid by using the critical section in the post routine?!
[EventBusTest.zip](https://github.com/spinettaro/delphi-event-bus/files/3934992/EventBusTest.zip)
Kind regards,
Detlef Schweng.

**Comment by spinettaro** [comment]
Hi @chomps1 , I understood your problem. First of all calling the EventBus to post an event inside an another event is an anti-pattern, this is a symptom that there is something that could be handle different in your application (probably bettter). There is a lock there because of the TObjectDictionary, so in reading is thread safe, no problems at all but someone could writes to the location you're reading from (the dictionary), and if you are reading in a "bad time" while someone else has started to write but didn't finish you could get garbage data. The risk is very low but could be verified that situation and to be a thread safe framework we need that lock. Hope I was clear. Let me know if not or if we could improve and solve that problem in a different way.

**Comment by chomps1** [comment]
Hi Danielle, thank you very much for your reply. This can be soved by using TMultiReadExclusiveWriteSynchronizer instead of TCriticalSection. Please have a look on the changes I made.

**Comment by spinettaro** [comment]
Thanks for PR @chomps1
