### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by skamradt** [spinettaro/delphi-event-bus#27]
TEventBus.Post makes a clone of the event, and this clone is never freed.  This causes a build up of event objects in memory.

**Comment by Geont** [comment]
There shouldn't be as you are responsible for freeing event object in every subscribed event handler.

**Comment by skamradt** [comment]
Ah, that wasn't very clear in the sample simple usage on the main page.

**Comment by spinettaro** [comment]
@skamradt as @Geont wrote you have to free the Event. This because the event is cloned every time as DEB have to face with different thread modes. In that case you have an asynchronous flow and consequentially every subscriber needs its event. As you suggested I'll update the readme to make it more clear.
